Registering the init scripts

diff --git a/debian/biometric-auth.postinst b/debian/biometric-auth.postinst
--- a/debian/biometric-auth.postinst
+++ b/debian/biometric-auth.postinst
@@ -23,6 +23,13 @@ else
 	# cleaned up on purge. Also remove old symlinks.
 	deb-systemd-helper update-state biometric-authentication.service >/dev/null || true
 fi
+
+# Automatically added by dh_installinit/11.3.2ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+        if [ -x "/etc/init.d/biometric-authentication" ]; then
+                update-rc.d lightdm biometric-authentication >/dev/null || exit 1
+        fi
+fi
 # End automatically added section
 
 exit 0
